
- name: Install required packages
  apt:
    name: ['lsb-release', 'curl', 'gpg']
    state: present
    update_cache: yes


- name: Create keyring dir
  file:
    path: /usr/share/keyrings
    state: directory

- name: Add Redis GPG key
  shell: |
    curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/redis-archive-keyring.gpg

- name: Set permissions on GPG key
  file:
    path: /usr/share/keyrings/redis-archive-keyring.gpg
    mode: '0644'

- name: Add Redis APT repo
  copy:
    dest: /etc/apt/sources.list.d/redis.list
    content: "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb {{ ansible_lsb.codename }} main"

- name: Update APT
  apt:
    update_cache: yes

- name: Install Redis Server
  apt:
    name: redis-server
    state: present

- name: Install redis-sentinel
  apt:
    name: redis-sentinel
    state: present


# - name: Enable Redis service
#   systemd:
#     name: redis-server
#     enabled: yes

