- name: Deploy custom config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"

- name: Deploy systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"


- name: Force systemd to reread configs (systemctl daemon-reload)
  ansible.builtin.systemd_service:
    daemon_reload: true


- name: Start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
