

- name: Download Apache Kafka
  ansible.builtin.get_url:
    url: '{{ kafka_download_url }}'
    dest: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    mode: 0644
  register: kafka_download


- name: Unpack Apache Kafka
  ansible.builtin.unarchive:
    src: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: '{{ kafka_root_dir }}'
    remote_src: true
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    extra_opts: ["--strip-components=1"]

- name: Create symlinks for Kafka binaries in /usr/local/bin
  ansible.builtin.file:
    src: "{{ kafka_root_dir }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kafka-server-start.sh
    - kafka-server-stop.sh
    - kafka-topics.sh
    - kafka-console-producer.sh
    - kafka-console-consumer.sh
    - kafka-consumer-groups.sh



