- name: Creating node_exporter user group
  ansible.builtin.group:
    name: '{{ node_exporter_group }}'
    state: present
    system: true

- name: Creating node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    system: yes
    shell: "/sbin/nologin"
    createhome: "no"
    state: present



- name: Install prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: true

- name: Copy prometheus node exporter file to bin
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    remote_src: true
    mode: 0755

- name: Copy systemd init file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: '{{ node_exporter_user }}'
    group: '{{ node_exporter_group }}'
    mode: '0644'

- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start node_exporter service
  service:
    name: node_exporter
    state: started
    enabled: true
