
mongodb_wiredtiger_cache_size_gb: "1"
mongodb_user: "mongodb"
mongodb_group: "mongodb"

mongodb_port: "27017"
mongodb_data_dir: "/data/mongodb/data"
mongodb_log_dir: "/data/mongodb/log"
mongodb_root_dir: ""
mongodb_replset_name: "rs0"

#Keepalived config
vip_address: "192.168.100.30"
vip_interface: "eth1"

# Node Exporter
node_exporter_user: "node_exporter"

node_exporter_group: "node_exporter"
node_exporter_version: "1.12.1"