- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: true

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent

- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load required kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Set kernel parameters for kubernetes
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { key: "net.ipv4.ip_forward", value: "1" }
    - { key: "fs.file-max", value: "500000" }
    - { key: "fs.inotify.max_user_watches", value: "524288" }
    - { key: "net.ipv4.ip_local_port_range", value: "10240 65535" }
    - { key: "net.core.somaxconn", value: "65535" }
    - { key: "net.ipv4.tcp_max_syn_backlog", value: "65535" }



- name: Apply Sysctl
  shell: sysctl --system

- name: Install dependencies
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gpg
      - bash-completion
    update_cache: yes


