- name: Create mongodb group
  ansible.builtin.group:
    name: '{{ mongodb_group }}'
    state: present
    system: true

- name: Create mongodb user
  ansible.builtin.user:
    name: '{{ mongodb_user }}'
    group: '{{ mongodb_group }}'
    state: present
    createhome: false
    system: true
    shell: /usr/sbin/nologin

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: '{{ mongodb_user }}'
    group: '{{ mongodb_group }}'
    mode: "0750"
  loop:
    - "{{ mongodb_data_dir }}"
    - "{{ mongodb_log_dir }}"
#    - "{{ mongodb_root_dir }}"
