- name: Copy custom redis.conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    mode: '0644'
  # notify: Restart Redis

- name: Copy custom sentinel.conf
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    mode: '0644'
  # notify: Restart Sentinel

- name: Copy custom systemd redis
  template:
    src: systemd-redis.service.j2
    dest: /etc/systemd/system/redis-server.service
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    mode: '0644'
  # notify: Restart Redis

- name: Copy custom sentinel.conf
  template:
    src: systemd-sentinel.service.j2
    dest: /etc/systemd/system/redis-sentinel.service
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    mode: '0644'
  # notify: Restart Sentinel


- name: Force systemd to reread configs (systemctl daemon-reload)
  ansible.builtin.systemd_service:
    daemon_reload: true