[mongodb]
mongodb-1 ansible_host= node_role= keepalived_priority=101 mongodb_priority=10
mongodb-2 ansible_host= node_role= keepalived_priority=100 mongodb_priority=5
mongodb-3 ansible_host= node_role= keepalived_priority=99 mongodb_priority=5

[mongodb-primary]
mongodb-1 ansible_host=

[loadbalancer]
lb-svr ansible_host= node_role=lb


[mongodb:vars]
ansible_user=
ansible_password=
ansible_become=true
