[mongodb]
mongo1 ansible_host= node_role= keepalived_priority=101
mongo2 ansible_host= node_role= keepalived_priority=100
mongo3 ansible_host= node_role= keepalived_priority=99

[loadbalancer]
lb-svr ansible_host= node_role=lb


[mongodb:vars]
ansible_user=
ansible_password=
ansible_become=true
