[k8s]
master-1 ansible_host= node_role=master keepalived_priority=101
master-2 ansible_host= node_role=master keepalived_priority=100
master-3 ansible_host= node_role=master keepalived_priority=99
worker-1 ansible_host= node_role=worker
worker-2 ansible_host= node_role=worker
worker-3 ansible_host= node_role=worker

[master_init]
master-1

[master_join]
master-2
master-3

[masters]
master-1
master-2
master-3

[workers]
worker-1
worker-2
worker-3

[all:vars]
sentinel_master=
ansible_become=true
become_ask_pass=false
vip_master=
