kubernetes_version: "1.36.1"
kubernetes_major_minor: "1.36"




vip_interface: "eth1"
ROUTER_ID: 51
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
cri_o_versions: "v1.36"
crictl_version: "1.36.0"
cni_plugin: "calico"
calico_version: "3.32.0"

criSocket: "unix:///var/run/crio/crio.sock"




#Load HAproxy
api_server_be_port: "6443"
api_server_fe_port: "8443"
control_plane_endpoint: "{{ vip_master }}:{{ api_server_fe_port }}"
