[redis]
sentinel-1 ansible_host= node_role=master
sentinel-2 ansible_host= node_role=replicas
sentinel-3 ansible_host= node_role=replicas

[redis_master]
sentinel-1 ansible_host=

[redis_replicas]
sentinel-2 ansible_host=
sentinel-3 ansible_host=

[all:vars]
sentinel_master=